INSERT INTO client (name, email, password) VALUES ('client 1', 'email1@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 2', 'email2@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 3', 'email3@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 4', 'email4@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 5', 'email5@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 6', 'email6@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 7', 'email7@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 8', 'email8@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 9', 'email9@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 10', 'email10@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 11', 'email11@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 12', 'email12@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 13', 'email13@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 14', 'email14@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 15', 'email15@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 16', 'email16@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 17', 'email17@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 18', 'email18@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 19', 'email19@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 20', 'email20@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 21', 'email21@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 22', 'email22@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 23', 'email23@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 24', 'email24@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 25', 'email25@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 26', 'email26@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 27', 'email27@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 28', 'email28@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 29', 'email29@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 30', 'email30@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 31', 'email31@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 32', 'email32@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 33', 'email33@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 34', 'email34@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 35', 'email35@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 36', 'email36@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 37', 'email37@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 38', 'email38@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 39', 'email39@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 40', 'email40@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 41', 'email41@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 42', 'email42@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 43', 'email43@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 44', 'email44@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 45', 'email45@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 46', 'email46@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 47', 'email47@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 48', 'email48@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 49', 'email49@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 50', 'email50@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 51', 'email51@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 52', 'email52@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 53', 'email53@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 54', 'email54@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 55', 'email55@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 56', 'email56@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 57', 'email57@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 58', 'email58@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 59', 'email59@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 60', 'email60@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 61', 'email61@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 62', 'email62@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 63', 'email63@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 64', 'email64@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 65', 'email65@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 66', 'email66@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 67', 'email67@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 68', 'email68@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 69', 'email69@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 70', 'email70@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 71', 'email71@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 72', 'email72@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 73', 'email73@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 74', 'email74@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 75', 'email75@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 76', 'email76@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 77', 'email77@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 78', 'email78@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 79', 'email79@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 80', 'email80@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 81', 'email81@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 82', 'email82@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 83', 'email83@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 84', 'email84@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 85', 'email85@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 86', 'email86@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 87', 'email87@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 88', 'email88@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 89', 'email89@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 90', 'email90@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 91', 'email91@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 92', 'email92@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 93', 'email93@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 94', 'email94@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 95', 'email95@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 96', 'email96@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 97', 'email97@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 98', 'email98@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 99', 'email99@gmail.com', '1234');
INSERT INTO client (name, email, password) VALUES ('client 100', 'email100@gmail.com', '1234');

INSERT INTO product (name, type, description, price) values ('product 1', 'type 4', 'description 1', 4734);
INSERT INTO product (name, type, description, price) values ('product 2', 'type 6', 'description 2', 7528);
INSERT INTO product (name, type, description, price) values ('product 3', 'type 4', 'description 3', 2376);
INSERT INTO product (name, type, description, price) values ('product 4', 'type 12', 'description 4', 6359);
INSERT INTO product (name, type, description, price) values ('product 5', 'type 8', 'description 5', 8546);
INSERT INTO product (name, type, description, price) values ('product 6', 'type 6', 'description 6', 9165);
INSERT INTO product (name, type, description, price) values ('product 7', 'type 5', 'description 7', 1268);
INSERT INTO product (name, type, description, price) values ('product 8', 'type 13', 'description 8', 537);
INSERT INTO product (name, type, description, price) values ('product 9', 'type 9', 'description 9', 9628);
INSERT INTO product (name, type, description, price) values ('product 10', 'type 6', 'description 10', 7784);
INSERT INTO product (name, type, description, price) values ('product 11', 'type 14', 'description 11', 9397);
INSERT INTO product (name, type, description, price) values ('product 12', 'type 12', 'description 12', 7974);
INSERT INTO product (name, type, description, price) values ('product 13', 'type 6', 'description 13', 5380);
INSERT INTO product (name, type, description, price) values ('product 14', 'type 5', 'description 14', 8768);
INSERT INTO product (name, type, description, price) values ('product 15', 'type 2', 'description 15', 1321);
INSERT INTO product (name, type, description, price) values ('product 16', 'type 14', 'description 16', 7400);
INSERT INTO product (name, type, description, price) values ('product 17', 'type 3', 'description 17', 2022);
INSERT INTO product (name, type, description, price) values ('product 18', 'type 4', 'description 18', 950);
INSERT INTO product (name, type, description, price) values ('product 19', 'type 15', 'description 19', 7261);
INSERT INTO product (name, type, description, price) values ('product 20', 'type 11', 'description 20', 5540);
INSERT INTO product (name, type, description, price) values ('product 21', 'type 2', 'description 21', 7053);
INSERT INTO product (name, type, description, price) values ('product 22', 'type 11', 'description 22', 443);
INSERT INTO product (name, type, description, price) values ('product 23', 'type 2', 'description 23', 4674);
INSERT INTO product (name, type, description, price) values ('product 24', 'type 10', 'description 24', 4499);
INSERT INTO product (name, type, description, price) values ('product 25', 'type 5', 'description 25', 5821);
INSERT INTO product (name, type, description, price) values ('product 26', 'type 8', 'description 26', 4213);
INSERT INTO product (name, type, description, price) values ('product 27', 'type 13', 'description 27', 6372);
INSERT INTO product (name, type, description, price) values ('product 28', 'type 9', 'description 28', 1151);
INSERT INTO product (name, type, description, price) values ('product 29', 'type 6', 'description 29', 2197);
INSERT INTO product (name, type, description, price) values ('product 30', 'type 2', 'description 30', 5677);
INSERT INTO product (name, type, description, price) values ('product 31', 'type 11', 'description 31', 8648);
INSERT INTO product (name, type, description, price) values ('product 32', 'type 14', 'description 32', 8218);
INSERT INTO product (name, type, description, price) values ('product 33', 'type 8', 'description 33', 6020);
INSERT INTO product (name, type, description, price) values ('product 34', 'type 14', 'description 34', 3238);
INSERT INTO product (name, type, description, price) values ('product 35', 'type 8', 'description 35', 8572);
INSERT INTO product (name, type, description, price) values ('product 36', 'type 2', 'description 36', 1359);
INSERT INTO product (name, type, description, price) values ('product 37', 'type 12', 'description 37', 2715);
INSERT INTO product (name, type, description, price) values ('product 38', 'type 11', 'description 38', 6095);
INSERT INTO product (name, type, description, price) values ('product 39', 'type 13', 'description 39', 1272);
INSERT INTO product (name, type, description, price) values ('product 40', 'type 9', 'description 40', 2125);
INSERT INTO product (name, type, description, price) values ('product 41', 'type 12', 'description 41', 8433);
INSERT INTO product (name, type, description, price) values ('product 42', 'type 12', 'description 42', 5241);
INSERT INTO product (name, type, description, price) values ('product 43', 'type 7', 'description 43', 1167);
INSERT INTO product (name, type, description, price) values ('product 44', 'type 2', 'description 44', 919);
INSERT INTO product (name, type, description, price) values ('product 45', 'type 4', 'description 45', 1049);
INSERT INTO product (name, type, description, price) values ('product 46', 'type 1', 'description 46', 7938);
INSERT INTO product (name, type, description, price) values ('product 47', 'type 13', 'description 47', 8499);
INSERT INTO product (name, type, description, price) values ('product 48', 'type 10', 'description 48', 9912);
INSERT INTO product (name, type, description, price) values ('product 49', 'type 3', 'description 49', 424);
INSERT INTO product (name, type, description, price) values ('product 50', 'type 6', 'description 50', 9011);

